// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8BLgJBelkRx_FPJs1Vzk-9uv5vGsKfxM',
    appId: '1:42230574747:web:7d0cd7d3527d37143b203e',
    messagingSenderId: '42230574747',
    projectId: 'momento-ai-6272d',
    authDomain: 'momento-ai-6272d.firebaseapp.com',
    storageBucket: 'momento-ai-6272d.firebasestorage.app',
    measurementId: 'G-GDJE6B553B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrTUVqJacEENHEMwy2kTQimRTZCe2gdk',
    appId: '1:42230574747:android:9f4ae202cf93e2c23b203e',
    messagingSenderId: '42230574747',
    projectId: 'momento-ai-6272d',
    storageBucket: 'momento-ai-6272d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlM-bwNRYDo3t5VPX32zCoW8jdFOLO2Wo',
    appId: '1:42230574747:ios:b49012103a51d1783b203e',
    messagingSenderId: '42230574747',
    projectId: 'momento-ai-6272d',
    storageBucket: 'momento-ai-6272d.firebasestorage.app',
    iosClientId: '42230574747-2iajnedqn2fhto25ks8u58vm8ak5alk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.momentoaiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlM-bwNRYDo3t5VPX32zCoW8jdFOLO2Wo',
    appId: '1:42230574747:ios:b49012103a51d1783b203e',
    messagingSenderId: '42230574747',
    projectId: 'momento-ai-6272d',
    storageBucket: 'momento-ai-6272d.firebasestorage.app',
    iosClientId: '42230574747-2iajnedqn2fhto25ks8u58vm8ak5alk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.momentoaiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8BLgJBelkRx_FPJs1Vzk-9uv5vGsKfxM',
    appId: '1:42230574747:web:15cd819d9cdf4eae3b203e',
    messagingSenderId: '42230574747',
    projectId: 'momento-ai-6272d',
    authDomain: 'momento-ai-6272d.firebaseapp.com',
    storageBucket: 'momento-ai-6272d.firebasestorage.app',
    measurementId: 'G-VL1HT2QMQT',
  );
}
